---
- name: Install Docker GPG Key
  apt_key:
    id: 7EA0A9C3F273FCD8
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Install Docker Repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install Docker Packages
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
    autoclean: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Ensuring docker service is always running
  systemd:
    enabled: yes
    state: started
    name: docker
